<?php
/** @var Magento\Framework\Escaper $escaper */
/** @var Magento\Framework\View\Element\Template $block */
/** @var Denal05\Ad0e702ExerciseEavRepository\ViewModel\ProductRenderer $productRendererViewModel **/
$productRendererViewModel = $block->getData('productRendererViewModel');
$productRepository = $productRendererViewModel->getProductRepository();
$searchCriteriaBuilder = $productRendererViewModel->getSearchCriteriaBuilder();
?>
<h1><?= __("Welcome") ?></h1>
<code><?= date("Y-m-d H:i:s") ?></code>

<p>
<?php if(!$productRepository): ?>
    <?= __('No product was found. ¯\_(ツ)_/¯') ?>
<?php else: ?>
    <?php
    $count = 1;
    $searchCriteriaBuilder->setCurrentPage(1);
    $searchCriteriaBuilder->setPageSize(10);
    $searchCriteriaBuilder->addFilter('type_id', \Magento\Catalog\Model\Product\Type::TYPE_SIMPLE, 'eq');
    $searchResult =  $productRepository->getList($searchCriteriaBuilder->create());
    foreach ($searchResult->getItems() as $product) {
        echo '<p>' . $count++ . ' | ' . $product->getSku();
    }
    ?>
    <p> repository searchResult->getTotalCount() = <?= $searchResult->getTotalCount() ?> products
<?php endif; ?>
</p>
